apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      defaultDatabase: default
      port: 8123
      protocol: http
      server: clickhouse
      username: default
    secureJsonData:
      password: ""
